##################################################
#            INTRO TO MAKE: SLIDE 1              #
##################################################

# Make is a tool for build automation.

# A Makefile consists of rules. A rule follows a
# specific structure:

all: dist/post.html

dist/post.html: src/post.md
	markdown src/post.md > dist/post.html

# Try running the following:
# make

# Now try running it again. What happened?
